Improving some scripts

diff --git a/git/bin/touched-files b/git/bin/touched-files
--- a/git/bin/touched-files
+++ b/git/bin/touched-files
@@ -1,15 +1,18 @@
 #!/bin/sh
 
+# If any of the following fails, the script fails.
+set -e
+
 if [ $# -lt 1 ]
 then
-	echo "Find files touched by branch of current HEAD, compared to another branch"
-	echo ""
-	echo "USAGE: $0 [-g] <other-branch>"
-	echo ""
-	echo "       -g  Group by directory"
-	echo ""
-	echo "EXAMPLE: $0 master"
-	exit 1
+  echo "Find files touched (differing) between HEAD and another branch"
+  echo ""
+  echo "USAGE: $0 [-g] <other-branch>"
+  echo ""
+  echo "       -g  Group by directory"
+  echo ""
+  echo "EXAMPLE: $0 master"
+  exit 1
 fi
 
 reference=$1
@@ -18,11 +21,11 @@ then
   reference=$2
 fi
 
-files=`git diff --name-only $reference...head`
+files="git diff -z --name-only $reference..HEAD"
 
 if [ $# -eq 1 ]
 then
-  echo "$files" | uniq | sort
+  $files | xargs --null --max-lines=1 echo | sort | uniq
 else
-  echo "$files" | xargs --max-lines=1 dirname | uniq | sort
+  $files | xargs --null --max-lines=1 dirname | sort | uniq
 fi
