Cache function output and return value

diff --git a/zsh/functions/startup/build-cache b/zsh/functions/startup/build-cache
--- a/zsh/functions/startup/build-cache
+++ b/zsh/functions/startup/build-cache
@@ -1,22 +1,36 @@
 local -a functions
-functions=(platform)
+if [[ "$#" -eq 0 ]]; then
+  functions=(platform is-mintty)
+else
+  functions=($@)
+fi
 
 # A global variable is needed since we cannot capture closures in zsh.
-typeset -gA function_cache
+typeset -gA _function_cache
 
 local fun
 for fun in $functions; do
   # Call function.
-  local result="$($fun)"
+  local result=''
+  result="$($fun)"
 
-  # Put result in cache.
-  function_cache[$fun]="$result"
+  # Put exit status and output in cache.
+  _function_cache[${fun}_exit_code]=$?
+  _function_cache[${fun}_output]="$result"
 
-  verbose Caching result of $fg[red]$fun$reset_color as $fg[green]${function_cache[$fun]}$reset_color
+  verbose Caching result of $fg[red]$fun$reset_color \
+    with output $fg[green]\"${_function_cache[${fun}_output]}\"$reset_color \
+    and exit code $fg[green]${_function_cache[${fun}_exit_code]}$reset_color
 
   # Redefine function to return result.
   function $fun () {
     local fun=$0
-    echo "${function_cache[$fun]}"
+
+    local output="${_function_cache[${fun}_output]}"
+    if [[ -n "$output" ]]; then
+      echo $output
+    fi
+
+    return ${_function_cache[${fun}_exit_code]}
   }
 done
