docker: log failed pulls during dpull instead of failing

diff --git a/docker/bin/dpull b/docker/bin/dpull
--- a/docker/bin/dpull
+++ b/docker/bin/dpull
@@ -21,8 +21,10 @@ docker image \
   grep --invert-match ':<none>' |
   while read -r image; do
     if ! is-local "$image"; then
-      docker image \
-             pull \
-             "$image"
+      if ! docker image \
+                  pull \
+                  "$image"; then
+        printf 'Failed pulling %s\n' "$image"
+      fi
     fi
   done
